/// Lightweight EN/FR string bundle per Orynta_SRS.md FR-7.2
/// (English + French at MVP). Kept as plain Dart maps rather than
/// generated ARB files so new strings are trivial to add during
/// active MVP development.
class AppStrings {
  final String languageCode;

  const AppStrings._(this.languageCode, this._values);

  final Map<String, String> _values;

  String call(String key) => _values[key] ?? key;

  static const AppStrings en = AppStrings._('en', _en);
  static const AppStrings fr = AppStrings._('fr', _fr);

  static AppStrings of(String code) => code == 'fr' ? fr : en;
}

const Map<String, String> _en = {
  'appName': 'Orynta',
  'tagline': 'Grow smarter, farm better',
  'onboardingWelcome': 'Your personal agronomist,\nin your pocket.',
  'onboardingSub':
      'Scan your soil and crops, get real answers, even without a connection.',
  'chooseLanguage': 'Choose your language',
  'getStarted': 'Get started',
  'english': 'English',
  'french': 'Français',
  'navHome': 'Home',
  'navScan': 'Scan',
  'navMarket': 'Market',
  'navProfile': 'Profile',
  'homeGreeting': 'Hello, {name}',
  'homeOffline': 'No connection — showing your last saved advisory',
  'weatherThisWeek': 'This week',
  'weatherAction': 'Recommended action',
  'quickScanSoil': 'Scan soil',
  'quickScanLeaf': 'Scan a leaf',
  'recentScans': 'Recent scans',
  'noScansYet': 'No scans yet — try scanning your soil or a leaf.',
  'scanTitle': 'Scan',
  'scanSoilTitle': 'Soil scan',
  'scanLeafTitle': 'Leaf & crop health',
  'scanSoilDesc': 'Photograph a soil sample to get soil type, fertility, and recommended crops.',
  'scanLeafDesc': 'Photograph a leaf to check for pests and disease.',
  'takePhoto': 'Take photo',
  'chooseFromGallery': 'Choose from gallery',
  'analyzing': 'Analyzing your photo…',
  'analyzingSub': 'This usually takes a few seconds.',
  'confidenceHigh': 'High confidence',
  'confidenceMedium': 'Medium confidence',
  'confidenceLow': 'Needs review',
  'escalationNotice':
      "We're not fully sure. An agronomist will review your photo and get back to you.",
  'soilType': 'Soil type',
  'fertility': 'Fertility',
  'recommendedCrops': 'Recommended crops',
  'whyThisResult': 'Why this result',
  'diagnosis': 'Diagnosis',
  'treatment': 'What to do',
  'nearestSuppliers': 'Nearest suppliers',
  'saveScan': 'Save to my plot',
  'scanSaved': 'Saved to your plot',
  'scanAnother': 'Scan another',
  'backToHome': 'Back to home',
  'marketTitle': 'Market',
  'myListings': 'My listings',
  'addListing': 'List produce for sale',
  'priceTrend': 'Indicative price trend',
  'suppliers': 'Input suppliers',
  'noListings': 'You have no active listings.',
  'crop': 'Crop',
  'quantity': 'Quantity',
  'readyDate': 'Ready date',
  'contactSupplier': 'Contact',
  'edit': 'Edit',
  'delete': 'Delete',
  'editListing': 'Edit listing',
  'deleteListing': 'Delete listing',
  'deleteListingConfirm': 'Delete this listing? This cannot be undone.',
  'deleteScanConfirm': 'Delete this scan? This cannot be undone.',
  'status': 'Status',
  'statusActive': 'Active',
  'statusPending': 'Pending',
  'statusSold': 'Sold',
  'profileTitle': 'Profile',
  'myData': 'My data',
  'viewMyData': 'View my data',
  'exportMyData': 'Export my data',
  'deleteMyData': 'Request deletion',
  'language': 'Language',
  'about': 'About Orynta',
  'aboutBody':
      'Orynta puts real, localized agronomic intelligence into every farmer\'s hand — on the phone you already own, in the language you already speak, with or without a data connection.',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'deleteConfirm': 'This will queue your data for permanent deletion. Continue?',
  'dataRequestQueued': 'Request queued. You\'ll be notified once processed.',
  'save': 'Save',
  'name': 'Name',
  'phone': 'Phone',
  'region': 'Region',
  'plot': 'Plot',
  'notifications': 'Notifications',
  'quickOverview': 'Quick overview',
  'soilHealthTrends': 'Soil health trends',
  'explore': 'Explore',
  'myCrops': 'My crops',
  'community': 'AgriForum',
  'plantingGuide': 'Planting guide',
  'supportChat': 'Support chat',
  'viewAll': 'View all',
  'totalScans': 'Total scans',
  'cropsMonitored': 'Crops monitored',
  'healthScore': 'Health score',
  'notEnoughScanData': 'Scan your soil at least twice to see a health trend here.',
  'allScansTitle': 'All scans',
  'noSavedCrops': 'No saved crops yet — bookmark a recommendation from a soil scan result.',
  'saveToMyCrops': 'Save to My Crops',
  'askQuestion': 'Ask a question',
  'category': 'Category',
  'categoryPestControl': 'Pest control',
  'categorySoilHealth': 'Soil health',
  'categoryWeather': 'Weather',
  'categoryMarket': 'Market',
  'categoryGeneral': 'General',
  'shareYourThoughts': 'Share your thoughts...',
  'post': 'Post',
  'communityPost': 'Post',
  'comments': 'comments',
  'allCategories': 'All categories',
  'communityPosts': 'Community posts',
  'mostRecent': 'Most recent',
  'mostCommented': 'Most commented',
  'noForumPosts': 'No posts yet — be the first to ask a question.',
  'growthDuration': 'Growth duration',
  'waterNeeds': 'Water needs',
  'commonThreats': 'Common threats',
  'harvestNotes': 'How to harvest',
  'agriculturalOfficer': 'Agricultural Officer',
  'typeMessage': 'Type a message...',
  'markAllRead': 'Mark all read',
  'noNotifications': 'No notifications yet.',
  'editProfile': 'Edit profile',
  'cropFocus': 'Crop focus',
  'farmerType': 'Farmer type',
  'farmerTypeBeginner': 'Beginner farmer',
  'farmerTypeAdvanced': 'Advanced farmer',
  'farmerTypeCommercial': 'Commercial farmer',
  'farmerTypeSubsistence': 'Subsistence farmer',
  'farmerTypeOrganic': 'Organic enthusiast',
  'farmerTypeAgronomist': 'Agronomist',
  'farmerTypeOfficer': 'Agricultural officer',
  'helpAndSupport': 'Help & support',
  'messageOfficer': 'Message officer',
  'latestSoilScan': 'Latest soil scan',
  'viewFullReport': 'View full scan report',
  'quickTips': 'Quick tips',
  'savedRecommendations': 'Saved recommendations',
  'cropDirectory': 'Planting recommendations',
  'noCropsMatch': 'No crops match your search.',
  'allCrops': 'All crops',
  'categoryGrains': 'Grains',
  'categoryVegetables': 'Vegetables',
  'categoryFruits': 'Fruits',
  'categoryLegumes': 'Legumes',
  'categoryOther': 'Other',
  'savedToDashboard': 'Saved to your dashboard',
  'learnResources': 'Learn & resources',
  'articlesAndTips': 'Articles & tips',
  'plantingCalendarSection': 'Planting calendar',
  'plantingCalendarDesc': 'Season-by-season guidance for the crops you grow.',
  'minRead': 'min read',
  'categorySoilManagement': 'Soil management',
  'categoryPlantHealth': 'Plant health',
  'categoryTechnology': 'Technology',
  'categorySuccessStories': 'Success stories',
  'postTitle': 'Title',
  'bookmarks': 'Bookmarks',
  'topContributors': 'Top contributors',
  'pinPost': 'Pin post',
  'unpinPost': 'Unpin post',
  'announcements': 'Announcements',
  'pinnedTopics': 'Pinned topics',
  'searchForum': 'Search posts',
  'points': 'points',
  'noBookmarksYet': "You haven't bookmarked any posts yet.",
  'addPhoto': 'Add photo',
  'discover': 'Discover',
  'createListing': 'Create listing',
  'contactSeller': 'Contact seller',
  'reviews': 'Reviews',
  'inStock': 'In stock',
  'productName': 'Product name',
  'description': 'Description',
  'price': 'Price',
  'unit': 'Unit',
  'location': 'Location',
  'typeCrop': 'Crop',
  'typeMaterial': 'Material/supply',
  'typeEquipment': 'Equipment',
  'typeService': 'Service',
  'noProductsFound': 'No products match your search.',
  'noOwnListings': "You haven't listed anything yet.",
  'searchMarketplace': 'Search products',
  'quickStats': 'Quick stats',
  'recommendationsSaved': 'Recommendations saved',
  'forumContributions': 'Forum contributions',
  'recentActivity': 'Recent activity',
  'activityLog': 'Activity log',
  'viewAllActivity': 'View all activity',
  'noActivityYet': 'No activity yet — scan your soil, save a crop, or post in AgriForum.',
  'notificationPreferences': 'Notification preferences',
  'notifScanComplete': 'Scan results',
  'notifForumReply': 'Forum replies',
  'notifMarketUpdate': 'Marketplace updates',
  'notifOfficerMessage': 'Officer messages',
  'darkMode': 'Dark mode',
  'account': 'Account',
  'changePassword': 'Change password',
  'logOut': 'Log out',
  'logOutConfirm': 'Are you sure you want to log out?',
  'joined': 'Joined',
  'bio': 'Bio',
  'changePhoto': 'Change photo',
};

const Map<String, String> _fr = {
  'appName': 'Orynta',
  'tagline': 'Cultivez mieux, récoltez plus',
  'onboardingWelcome': 'Votre agronome personnel,\ndans votre poche.',
  'onboardingSub':
      'Scannez votre sol et vos cultures, obtenez de vraies réponses, même sans connexion.',
  'chooseLanguage': 'Choisissez votre langue',
  'getStarted': 'Commencer',
  'english': 'English',
  'french': 'Français',
  'navHome': 'Accueil',
  'navScan': 'Scanner',
  'navMarket': 'Marché',
  'navProfile': 'Profil',
  'homeGreeting': 'Bonjour, {name}',
  'homeOffline': 'Pas de connexion — dernier conseil enregistré affiché',
  'weatherThisWeek': 'Cette semaine',
  'weatherAction': 'Action recommandée',
  'quickScanSoil': 'Scanner le sol',
  'quickScanLeaf': 'Scanner une feuille',
  'recentScans': 'Scans récents',
  'noScansYet': 'Aucun scan pour le moment — scannez votre sol ou une feuille.',
  'scanTitle': 'Scanner',
  'scanSoilTitle': 'Analyse du sol',
  'scanLeafTitle': 'Santé des cultures',
  'scanSoilDesc':
      'Photographiez un échantillon de sol pour connaître son type, sa fertilité et les cultures recommandées.',
  'scanLeafDesc': 'Photographiez une feuille pour détecter maladies et ravageurs.',
  'takePhoto': 'Prendre une photo',
  'chooseFromGallery': 'Choisir dans la galerie',
  'analyzing': 'Analyse de votre photo…',
  'analyzingSub': 'Cela prend généralement quelques secondes.',
  'confidenceHigh': 'Confiance élevée',
  'confidenceMedium': 'Confiance moyenne',
  'confidenceLow': 'À vérifier',
  'escalationNotice':
      "Nous ne sommes pas entièrement sûrs. Un agronome examinera votre photo et vous répondra.",
  'soilType': 'Type de sol',
  'fertility': 'Fertilité',
  'recommendedCrops': 'Cultures recommandées',
  'whyThisResult': 'Pourquoi ce résultat',
  'diagnosis': 'Diagnostic',
  'treatment': 'Que faire',
  'nearestSuppliers': 'Fournisseurs proches',
  'saveScan': 'Enregistrer sur ma parcelle',
  'scanSaved': 'Enregistré sur votre parcelle',
  'scanAnother': 'Scanner à nouveau',
  'backToHome': 'Retour à l\'accueil',
  'marketTitle': 'Marché',
  'myListings': 'Mes annonces',
  'addListing': 'Mettre en vente',
  'priceTrend': 'Tendance des prix (indicative)',
  'suppliers': 'Fournisseurs d\'intrants',
  'noListings': 'Vous n\'avez aucune annonce active.',
  'crop': 'Culture',
  'quantity': 'Quantité',
  'readyDate': 'Date de disponibilité',
  'contactSupplier': 'Contacter',
  'edit': 'Modifier',
  'delete': 'Supprimer',
  'editListing': 'Modifier l\'annonce',
  'deleteListing': 'Supprimer l\'annonce',
  'deleteListingConfirm': 'Supprimer cette annonce ? Cette action est irréversible.',
  'deleteScanConfirm': 'Supprimer ce scan ? Cette action est irréversible.',
  'status': 'Statut',
  'statusActive': 'Active',
  'statusPending': 'En attente',
  'statusSold': 'Vendue',
  'profileTitle': 'Profil',
  'myData': 'Mes données',
  'viewMyData': 'Voir mes données',
  'exportMyData': 'Exporter mes données',
  'deleteMyData': 'Demander la suppression',
  'language': 'Langue',
  'about': 'À propos d\'Orynta',
  'aboutBody':
      'Orynta met une intelligence agronomique réelle et localisée entre les mains de chaque agriculteur — sur le téléphone qu\'il possède déjà, dans la langue qu\'il parle déjà, avec ou sans connexion.',
  'cancel': 'Annuler',
  'confirm': 'Confirmer',
  'deleteConfirm':
      'Vos données seront mises en file d\'attente pour suppression définitive. Continuer ?',
  'dataRequestQueued': 'Demande enregistrée. Vous serez notifié une fois traitée.',
  'save': 'Enregistrer',
  'name': 'Nom',
  'phone': 'Téléphone',
  'region': 'Région',
  'plot': 'Parcelle',
  'notifications': 'Notifications',
  'quickOverview': 'Aperçu rapide',
  'soilHealthTrends': 'Tendances de la santé du sol',
  'explore': 'Explorer',
  'myCrops': 'Mes cultures',
  'community': 'AgriForum',
  'plantingGuide': 'Guide de plantation',
  'supportChat': 'Assistance',
  'viewAll': 'Tout voir',
  'totalScans': 'Scans au total',
  'cropsMonitored': 'Cultures suivies',
  'healthScore': 'Score de santé',
  'notEnoughScanData': 'Scannez votre sol au moins deux fois pour voir une tendance ici.',
  'allScansTitle': 'Tous les scans',
  'noSavedCrops': 'Aucune culture enregistrée — enregistrez une recommandation depuis un résultat de scan de sol.',
  'saveToMyCrops': 'Enregistrer dans Mes cultures',
  'askQuestion': 'Poser une question',
  'category': 'Catégorie',
  'categoryPestControl': 'Lutte antiparasitaire',
  'categorySoilHealth': 'Santé du sol',
  'categoryWeather': 'Météo',
  'categoryMarket': 'Marché',
  'categoryGeneral': 'Général',
  'shareYourThoughts': 'Partagez vos pensées...',
  'post': 'Publier',
  'communityPost': 'Publication',
  'comments': 'commentaires',
  'allCategories': 'Toutes les catégories',
  'communityPosts': 'Publications de la communauté',
  'mostRecent': 'Plus récent',
  'mostCommented': 'Plus commenté',
  'noForumPosts': 'Aucune publication pour le moment — posez la première question.',
  'growthDuration': 'Durée de croissance',
  'waterNeeds': 'Besoins en eau',
  'commonThreats': 'Menaces courantes',
  'harvestNotes': 'Comment récolter',
  'agriculturalOfficer': 'Agent agricole',
  'typeMessage': 'Écrire un message...',
  'markAllRead': 'Tout marquer comme lu',
  'noNotifications': 'Aucune notification pour le moment.',
  'editProfile': 'Modifier le profil',
  'cropFocus': 'Culture principale',
  'farmerType': 'Type d\'agriculteur',
  'farmerTypeBeginner': 'Agriculteur débutant',
  'farmerTypeAdvanced': 'Agriculteur avancé',
  'farmerTypeCommercial': 'Agriculteur commercial',
  'farmerTypeSubsistence': 'Agriculteur de subsistance',
  'farmerTypeOrganic': 'Passionné de bio',
  'farmerTypeAgronomist': 'Agronome',
  'farmerTypeOfficer': 'Agent agricole',
  'helpAndSupport': 'Aide et assistance',
  'messageOfficer': 'Contacter l\'agent',
  'latestSoilScan': 'Dernier scan de sol',
  'viewFullReport': 'Voir le rapport complet',
  'quickTips': 'Astuces rapides',
  'savedRecommendations': 'Recommandations enregistrées',
  'cropDirectory': 'Recommandations de plantation',
  'noCropsMatch': 'Aucune culture ne correspond à votre recherche.',
  'allCrops': 'Toutes les cultures',
  'categoryGrains': 'Céréales',
  'categoryVegetables': 'Légumes',
  'categoryFruits': 'Fruits',
  'categoryLegumes': 'Légumineuses',
  'categoryOther': 'Autre',
  'savedToDashboard': 'Enregistré sur votre tableau de bord',
  'learnResources': 'Apprentissage et ressources',
  'articlesAndTips': 'Articles et astuces',
  'plantingCalendarSection': 'Calendrier de plantation',
  'plantingCalendarDesc': 'Conseils saisonniers pour vos cultures.',
  'minRead': 'min de lecture',
  'categorySoilManagement': 'Gestion du sol',
  'categoryPlantHealth': 'Santé des plantes',
  'categoryTechnology': 'Technologie',
  'categorySuccessStories': 'Réussites',
  'postTitle': 'Titre',
  'bookmarks': 'Favoris',
  'topContributors': 'Meilleurs contributeurs',
  'pinPost': 'Épingler',
  'unpinPost': 'Désépingler',
  'announcements': 'Annonces',
  'pinnedTopics': 'Sujets épinglés',
  'searchForum': 'Rechercher des publications',
  'points': 'points',
  'noBookmarksYet': "Vous n'avez encore aucune publication enregistrée.",
  'addPhoto': 'Ajouter une photo',
  'discover': 'Découvrir',
  'createListing': 'Créer une annonce',
  'contactSeller': 'Contacter le vendeur',
  'reviews': 'Avis',
  'inStock': 'En stock',
  'productName': 'Nom du produit',
  'description': 'Description',
  'price': 'Prix',
  'unit': 'Unité',
  'location': 'Emplacement',
  'typeCrop': 'Culture',
  'typeMaterial': 'Matériel/intrant',
  'typeEquipment': 'Équipement',
  'typeService': 'Service',
  'noProductsFound': 'Aucun produit ne correspond à votre recherche.',
  'noOwnListings': "Vous n'avez encore rien mis en vente.",
  'searchMarketplace': 'Rechercher des produits',
  'quickStats': 'Statistiques rapides',
  'recommendationsSaved': 'Recommandations enregistrées',
  'forumContributions': 'Contributions au forum',
  'recentActivity': 'Activité récente',
  'activityLog': 'Journal d\'activité',
  'viewAllActivity': 'Voir toute l\'activité',
  'noActivityYet': 'Aucune activité pour le moment — scannez votre sol, enregistrez une culture ou publiez sur AgriForum.',
  'notificationPreferences': 'Préférences de notification',
  'notifScanComplete': 'Résultats de scan',
  'notifForumReply': 'Réponses du forum',
  'notifMarketUpdate': 'Mises à jour du marché',
  'notifOfficerMessage': 'Messages de l\'agent',
  'darkMode': 'Mode sombre',
  'account': 'Compte',
  'changePassword': 'Changer le mot de passe',
  'logOut': 'Se déconnecter',
  'logOutConfirm': 'Voulez-vous vraiment vous déconnecter ?',
  'joined': 'Membre depuis',
  'bio': 'Bio',
  'changePhoto': 'Changer la photo',
};
