/// Lightweight EN/FR string bundle per Orynta_SRS.md FR-7.2
/// (English + French at MVP). Kept as plain Dart maps rather than
/// generated ARB files so new strings are trivial to add during
/// active MVP development.
class AppStrings {
  final String languageCode;

  const AppStrings._(this.languageCode, this._values);

  final Map<String, String> _values;

  String call(String key) => _values[key] ?? key;

  static const AppStrings en = AppStrings._('en', _en);
  static const AppStrings fr = AppStrings._('fr', _fr);

  static AppStrings of(String code) => code == 'fr' ? fr : en;
}

const Map<String, String> _en = {
  'appName': 'Orynta',
  'tagline': 'Grow smarter, farm better',
  'onboardingWelcome': 'Your personal agronomist,\nin your pocket.',
  'onboardingSub':
      'Scan your soil and crops, get real answers, even without a connection.',
  'chooseLanguage': 'Choose your language',
  'getStarted': 'Get started',
  'english': 'English',
  'french': 'Français',
  'navHome': 'Home',
  'navScan': 'Scan',
  'navMarket': 'Market',
  'navProfile': 'Profile',
  'homeGreeting': 'Hello, {name}',
  'homeOffline': 'No connection — showing your last saved advisory',
  'weatherThisWeek': 'This week',
  'weatherAction': 'Recommended action',
  'quickScanSoil': 'Scan soil',
  'quickScanLeaf': 'Scan a leaf',
  'recentScans': 'Recent scans',
  'noScansYet': 'No scans yet — try scanning your soil or a leaf.',
  'scanTitle': 'Scan',
  'scanSoilTitle': 'Soil scan',
  'scanLeafTitle': 'Leaf & crop health',
  'scanSoilDesc': 'Photograph a soil sample to get soil type, fertility, and recommended crops.',
  'scanLeafDesc': 'Photograph a leaf to check for pests and disease.',
  'takePhoto': 'Take photo',
  'chooseFromGallery': 'Choose from gallery',
  'analyzing': 'Analyzing your photo…',
  'analyzingSub': 'This usually takes a few seconds.',
  'confidenceHigh': 'High confidence',
  'confidenceMedium': 'Medium confidence',
  'confidenceLow': 'Needs review',
  'escalationNotice':
      "We're not fully sure. An agronomist will review your photo and get back to you.",
  'soilType': 'Soil type',
  'fertility': 'Fertility',
  'recommendedCrops': 'Recommended crops',
  'whyThisResult': 'Why this result',
  'diagnosis': 'Diagnosis',
  'treatment': 'What to do',
  'nearestSuppliers': 'Nearest suppliers',
  'saveScan': 'Save to my plot',
  'scanSaved': 'Saved to your plot',
  'scanAnother': 'Scan another',
  'backToHome': 'Back to home',
  'marketTitle': 'Market',
  'myListings': 'My listings',
  'addListing': 'List produce for sale',
  'priceTrend': 'Indicative price trend',
  'suppliers': 'Input suppliers',
  'noListings': 'You have no active listings.',
  'crop': 'Crop',
  'quantity': 'Quantity',
  'readyDate': 'Ready date',
  'contactSupplier': 'Contact',
  'profileTitle': 'Profile',
  'myData': 'My data',
  'viewMyData': 'View my data',
  'exportMyData': 'Export my data',
  'deleteMyData': 'Request deletion',
  'language': 'Language',
  'about': 'About Orynta',
  'aboutBody':
      'Orynta puts real, localized agronomic intelligence into every farmer\'s hand — on the phone you already own, in the language you already speak, with or without a data connection.',
  'cancel': 'Cancel',
  'confirm': 'Confirm',
  'deleteConfirm': 'This will queue your data for permanent deletion. Continue?',
  'dataRequestQueued': 'Request queued. You\'ll be notified once processed.',
  'save': 'Save',
  'name': 'Name',
  'phone': 'Phone',
  'region': 'Region',
  'plot': 'Plot',
};

const Map<String, String> _fr = {
  'appName': 'Orynta',
  'tagline': 'Cultivez mieux, récoltez plus',
  'onboardingWelcome': 'Votre agronome personnel,\ndans votre poche.',
  'onboardingSub':
      'Scannez votre sol et vos cultures, obtenez de vraies réponses, même sans connexion.',
  'chooseLanguage': 'Choisissez votre langue',
  'getStarted': 'Commencer',
  'english': 'English',
  'french': 'Français',
  'navHome': 'Accueil',
  'navScan': 'Scanner',
  'navMarket': 'Marché',
  'navProfile': 'Profil',
  'homeGreeting': 'Bonjour, {name}',
  'homeOffline': 'Pas de connexion — dernier conseil enregistré affiché',
  'weatherThisWeek': 'Cette semaine',
  'weatherAction': 'Action recommandée',
  'quickScanSoil': 'Scanner le sol',
  'quickScanLeaf': 'Scanner une feuille',
  'recentScans': 'Scans récents',
  'noScansYet': 'Aucun scan pour le moment — scannez votre sol ou une feuille.',
  'scanTitle': 'Scanner',
  'scanSoilTitle': 'Analyse du sol',
  'scanLeafTitle': 'Santé des cultures',
  'scanSoilDesc':
      'Photographiez un échantillon de sol pour connaître son type, sa fertilité et les cultures recommandées.',
  'scanLeafDesc': 'Photographiez une feuille pour détecter maladies et ravageurs.',
  'takePhoto': 'Prendre une photo',
  'chooseFromGallery': 'Choisir dans la galerie',
  'analyzing': 'Analyse de votre photo…',
  'analyzingSub': 'Cela prend généralement quelques secondes.',
  'confidenceHigh': 'Confiance élevée',
  'confidenceMedium': 'Confiance moyenne',
  'confidenceLow': 'À vérifier',
  'escalationNotice':
      "Nous ne sommes pas entièrement sûrs. Un agronome examinera votre photo et vous répondra.",
  'soilType': 'Type de sol',
  'fertility': 'Fertilité',
  'recommendedCrops': 'Cultures recommandées',
  'whyThisResult': 'Pourquoi ce résultat',
  'diagnosis': 'Diagnostic',
  'treatment': 'Que faire',
  'nearestSuppliers': 'Fournisseurs proches',
  'saveScan': 'Enregistrer sur ma parcelle',
  'scanSaved': 'Enregistré sur votre parcelle',
  'scanAnother': 'Scanner à nouveau',
  'backToHome': 'Retour à l\'accueil',
  'marketTitle': 'Marché',
  'myListings': 'Mes annonces',
  'addListing': 'Mettre en vente',
  'priceTrend': 'Tendance des prix (indicative)',
  'suppliers': 'Fournisseurs d\'intrants',
  'noListings': 'Vous n\'avez aucune annonce active.',
  'crop': 'Culture',
  'quantity': 'Quantité',
  'readyDate': 'Date de disponibilité',
  'contactSupplier': 'Contacter',
  'profileTitle': 'Profil',
  'myData': 'Mes données',
  'viewMyData': 'Voir mes données',
  'exportMyData': 'Exporter mes données',
  'deleteMyData': 'Demander la suppression',
  'language': 'Langue',
  'about': 'À propos d\'Orynta',
  'aboutBody':
      'Orynta met une intelligence agronomique réelle et localisée entre les mains de chaque agriculteur — sur le téléphone qu\'il possède déjà, dans la langue qu\'il parle déjà, avec ou sans connexion.',
  'cancel': 'Annuler',
  'confirm': 'Confirmer',
  'deleteConfirm':
      'Vos données seront mises en file d\'attente pour suppression définitive. Continuer ?',
  'dataRequestQueued': 'Demande enregistrée. Vous serez notifié une fois traitée.',
  'save': 'Enregistrer',
  'name': 'Nom',
  'phone': 'Téléphone',
  'region': 'Région',
  'plot': 'Parcelle',
};
